version: "3.2"

services:
  Mi-Panel:
    image: 'hslr/Mi-Panel:latest'
    container_name: Mi-Panel
    volumes:
    - ./conf:/app/conf
    - ./uploads:/app/uploads
    - ./database:/app/database
    # - ./runtime:/app/runtime
    ports:
    - 3002:3002
    restart: always